name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types: [published]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04  # 24.04ではなく22.04を使用
        rosdistro:
          - jazzy

    runs-on: ${{ matrix.os }}  # コンテナではなく直接Ubuntu上で実行

    steps:
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.rosdistro }}

      - name: Setup directories
        run: mkdir -p ros2_ws/src

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: ros2_ws/src/vision2motion

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-opencv

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install torch torchvision transformers pillow

      - name: Install ROS dependencies
        run: |
          cd ros2_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -y --rosdistro ${{ matrix.rosdistro }}

      - name: Build
        run: |
          cd ros2_ws
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh
          colcon build --symlink-install
          
      - name: Run tests
        run: |
          cd ros2_ws
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh
          colcon test
          colcon test-result --verbose