name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types: [published]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04  # Humble用のUbuntu 22.04
        rosdistro:
          - humble  # Jazzyから変更

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.rosdistro }}

      - name: Setup system
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y python3-pip python3-opencv

      - name: Create workspace
        run: mkdir -p ros2_ws/src

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ros2_ws/src/vision2motion

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip3 install transformers pillow

      - name: Install ROS dependencies
        run: |
          cd ros2_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -y --rosdistro ${{ matrix.rosdistro }}

      - name: Build
        run: |
          cd ros2_ws
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          colcon build --symlink-install

      - name: Test
        run: |
          cd ros2_ws
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          source install/setup.bash
#          colcon test
#          colcon test-result --verbose